(define (make-account balance passwd)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch secret method)
    (if (eq? secret passwd)
        (cond ((eq? method 'withdraw) withdraw)
              ((eq? method 'deposit) deposit)
              (else
                (error "Unknown request -- MAKE-ACCOUNT" method)))
        (lambda (x) "Incorrect password")))
  dispatch)

(define (make-joint account old-passwd new-passwd)
  (if (number? ((account old-passwd 'withdraw) 0))
      (lambda (secret method)
        (if (eq? secret new-passwd)
            (account old-passwd method)
            (lambda (x) "Incorrect password")))
      (error "Unknown account -- MAKE-JOINT" account)))


;; test
(define (println x)
  (display x)
  (newline))

(define peter-acc (make-account 100 'secret-password))
(define paul-acc (make-joint peter-acc 'secret-password 'rosebud))
(println ((peter-acc 'secret-password 'withdraw) 10))
(println ((paul-acc 'rosebud 'withdraw) 10))
(println ((peter-acc 'secret-password 'withdraw) 10))
(println ((paul-acc 'rosebud 'withdraw) 10))
(println ((paul-acc 'secret-password 'withdraw) 10))
